### ISSUE TITLE
prevent double detection of buildings (e.g. adjacency twice with vanilla capital submod)

### ISSUE THREAD

**Issue by Gra-tak** [GatekeeperHaig/Stellaris-Modding-Den#43]
basically teaching createAIVARSFromModifiers to use the file sorting used in cgm_automation_files. That way, I can remove buildings that are overwritten by cgm_buildings. It will get harder for cgm stuff that is overwritten by other mods... Probably needs an "is_active" flag in cgm.

**Comment by Goldziher** [comment]
Sounds good. Maybe you could output this into a different file - so a manual check can be done.
